In [1]:
from selenium import webdriver

In [2]:
import warnings
warnings.filterwarnings('ignore')
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.by import By
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [27]:
driver=webdriver.Chrome()

     ***************************** Webscraping for City - Dubai *****************************

In [7]:
driver.get('https://www.booking.com/searchresults.en-gb.html?label=yho748jc-1FCAEoggI46AdIM1gDaGyIAQGYAQm4ARfIAQzYAQHoAQH4AQyIAgGoAgO4AurS96YGwAIB0gIkMTJhN2VkNjAtYzc1MS00MjVhLTg3ZjYtMzI5ZWMzNzlkNzhm2AIG4AIB&sid=b8f957b39c045a637fc32a3a001d95d0&aid=397646&ss=Dubai&ssne=Dubai&ssne_untouched=Dubai&efdco=1&lang=en-gb&src=searchresults&dest_id=-782831&dest_type=city&checkin=2023-10-21&checkout=2023-10-22&ltfd=1%3A1%3A11-2023%3A1%3A1&group_adults=2&no_rooms=1&group_children=0&nflt=ht_id%3D204')

In [9]:
import pandas as pd


hotel_data = []

# Define the number of pages you want to scrape (5 in this case)
start_page = 1
end_page = 25

for page in range(start_page, end_page + 1):
    try:
        # Extract data using XPaths
        hotel_name_elements = driver.find_elements(By.XPATH, '//div[@class="f6431b446c a15b38c233"]')
        room_type_elements = driver.find_elements(By.XPATH, '//span[@class="e8f7c070a7"]')
        single_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        double_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        price_elements = driver.find_elements(By.XPATH, '//span[@class="f6431b446c fbfd7c1165 e84eb96b1f"]')
        
        num_elements = min(len(hotel_name_elements), len(room_type_elements), len(single_bed_elements), len(double_bed_elements), len(price_elements))
        
        for i in range(num_elements):
            hotel_name = hotel_name_elements[i].text
            room_type = room_type_elements[i].text if i < len(room_type_elements) else "N/A"
            
            # Check if the extracted text contains "single" and "double"
            single_bed_text = single_bed_elements[i].text if i < len(single_bed_elements) else "N/A"
            double_bed_text = double_bed_elements[i].text if i < len(double_bed_elements) else "N/A"
            
            single_bed = "Yes" if "single" in single_bed_text.lower() else "No"
            double_bed = "Yes" if "double" in double_bed_text.lower() else "No"
            
            price = price_elements[i].text if i < len(price_elements) else "N/A"

            # Store the data in a suitable data structure, e.g., a list of dictionaries
            hotel_data.append({
                "Hotel Name": hotel_name,
                "Room Type": room_type,
                "Single Bed": single_bed,
                "Double Bed": double_bed,
                "Price": price
            })
    except NoSuchElementException:
        # Handle the case when an element is not found
        hotel_data.append({
            "Hotel Name": "N/A",
            "Room Type": "N/A",
            "Single Bed": "N/A",
            "Double Bed": "N/A",
            "Price": "N/A"
        })
    
    try:
        # Click the "Next" button to navigate to the next page
        nxt_button = driver.find_element(By.XPATH, '//div[@class="b16a89683f cab1524053"]')
        nxt_button.click()
    except NoSuchElementException:
        # Handle the case when the "Next" button is not found
        print("Next button not found. Exiting the loop.")
        break
    
    # Add a short delay to allow the next page to load
    time.sleep(2)

# Create a DataFrame from the scraped data
df_Dubai = pd.DataFrame(hotel_data)

# Print the DataFrame
print(df_Dubai)

Next button not found. Exiting the loop.
                                          Hotel Name  \
0                               Edge Creekside Hotel
1                                Sonder Business Bay
2                    ibis Styles Dubai Airport Hotel
3                                   Resivation Hotel
4    Holiday Inn Express Dubai Airport, an IHG Hotel
..                                               ...
610                          Marina Hotel Apartments
611                 Tamani Marina Hotel & Apartments
612                          Al Waleed Holiday Homes
613                     Royal Plaza Hotel Apartments
614             Al Khoory Hotel Apartments Al Barsha

                                             Room Type Single Bed Double Bed  \
0                                     Deluxe King Room         No        Yes
1                                   Standard Apartment         No        Yes
2    Twin Room - Free DXB Airport Shuttle Drop Off,...        Yes         No
3                                   Superior King Room         No        Yes
4    Double Room - Smoking (Free Shuttle Bus to Air...         No        Yes
..                                                 ...        ...        ...
610                              One-Bedroom Apartment         No        Yes
611                              Two-Bedroom Apartment        Yes        Yes
612  One-Bedroom Apartment (2 Adults) with 20% off F&B         No        Yes
613                          Executive 2-Bedroom Suite        Yes        Yes
614                                             Studio         No        Yes

        Price
0    ₹ 10,550
1    ₹ 21,283
2     ₹ 7,933
3     ₹ 7,241
4     ₹ 7,290
..        ...
610  ₹ 14,044
611  ₹ 23,217
612  ₹ 12,232
613  ₹ 10,183
614   ₹ 9,780

[615 rows x 5 columns]

In [11]:
df_Dubai.head()

,Hotel Name,Room Type,Single Bed,Double Bed,Price
0,Edge Creekside Hotel,Deluxe King Room,No,Yes,"₹ 10,550"
1,Sonder Business Bay,Standard Apartment,No,Yes,"₹ 21,283"
2,ibis Styles Dubai Airport Hotel,"Twin Room - Free DXB Airport Shuttle Drop Off,...",Yes,No,"₹ 7,933"
3,Resivation Hotel,Superior King Room,No,Yes,"₹ 7,241"
4,"Holiday Inn Express Dubai Airport, an IHG Hotel",Double Room - Smoking (Free Shuttle Bus to Air...,No,Yes,"₹ 7,290"

                ************** WebScraping for City - London *********************

In [13]:
driver.get('https://www.booking.com/searchresults.en-gb.html?label=yho748jc-1FCAEoggI46AdIM1gDaGyIAQGYAQm4ARfIAQzYAQHoAQH4AQyIAgGoAgO4AurS96YGwAIB0gIkMTJhN2VkNjAtYzc1MS00MjVhLTg3ZjYtMzI5ZWMzNzlkNzhm2AIG4AIB&sid=b8f957b39c045a637fc32a3a001d95d0&aid=397646&checkin=2023-11-06&checkout=2023-11-07&city=-2601889&nflt=ht_id%3D204')

In [14]:
import pandas as pd


hotel_data = []

# Define the number of pages you want to scrape (5 in this case)
start_page = 1
end_page = 25

for page in range(start_page, end_page + 1):
    try:
        # Extract data using XPaths
        hotel_name_elements = driver.find_elements(By.XPATH, '//div[@class="f6431b446c a15b38c233"]')
        room_type_elements = driver.find_elements(By.XPATH, '//span[@class="e8f7c070a7"]')
        single_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        double_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        price_elements = driver.find_elements(By.XPATH, '//span[@class="f6431b446c fbfd7c1165 e84eb96b1f"]')
        
        num_elements = min(len(hotel_name_elements), len(room_type_elements), len(single_bed_elements), len(double_bed_elements), len(price_elements))
        
        for i in range(num_elements):
            hotel_name = hotel_name_elements[i].text
            room_type = room_type_elements[i].text if i < len(room_type_elements) else "N/A"
            
            # Check if the extracted text contains "single" and "double"
            single_bed_text = single_bed_elements[i].text if i < len(single_bed_elements) else "N/A"
            double_bed_text = double_bed_elements[i].text if i < len(double_bed_elements) else "N/A"
            
            single_bed = "Yes" if "single" in single_bed_text.lower() else "No"
            double_bed = "Yes" if "double" in double_bed_text.lower() else "No"
            
            price = price_elements[i].text if i < len(price_elements) else "N/A"

            # Store the data in a suitable data structure, e.g., a list of dictionaries
            hotel_data.append({
                "Hotel Name": hotel_name,
                "Room Type": room_type,
                "Single Bed": single_bed,
                "Double Bed": double_bed,
                "Price": price
            })
    except NoSuchElementException:
        # Handle the case when an element is not found
        hotel_data.append({
            "Hotel Name": "N/A",
            "Room Type": "N/A",
            "Single Bed": "N/A",
            "Double Bed": "N/A",
            "Price": "N/A"
        })
    
    try:
        # Click the "Next" button to navigate to the next page
        nxt_button = driver.find_element(By.XPATH, '//div[@class="b16a89683f cab1524053"]')
        nxt_button.click()
    except NoSuchElementException:
        # Handle the case when the "Next" button is not found
        print("Next button not found. Exiting the loop.")
        break
    
    # Add a short delay to allow the next page to load
    time.sleep(2)

# Create a DataFrame from the scraped data
df_London = pd.DataFrame(hotel_data)

# Print the DataFrame
print(df_London)

                                      Hotel Name  \
0    Middle Eight - Preferred Hotels and Resorts
1                     The Carlton Tower Jumeirah
2                              Zedwell Greenwich
3            Maldron Hotel Finsbury Park, London
4         Zedwell Underground Tottenham Court Rd
..                                           ...
621                                Orlando hotel
622                  K+K Hotel George Kensington
623                                   The Goring
624                     Park Avenue Baker Street
625                           Gainsborough Hotel

                                             Room Type Single Bed Double Bed  \
0                                         Urban Deluxe         No        Yes
1    Superior Room with exclusive access to Cadogan...         No         No
2                                          Double Room         No        Yes
3                                   Deluxe Double Room         No        Yes
4                                             Cocoon 2         No        Yes
..                                                 ...        ...        ...
621                                 Standard Twin Room        Yes         No
622                                         Cosy Urban         No        Yes
623                       Superior Double or Twin Room         No        Yes
624                                 Deluxe Double Room         No        Yes
625                                        Double Room         No        Yes

        Price
0    ₹ 35,344
1    ₹ 82,887
2    ₹ 11,714
3    ₹ 17,167
4    ₹ 13,128
..        ...
621   ₹ 7,877
622  ₹ 22,630
623  ₹ 76,243
624  ₹ 16,481
625  ₹ 20,096

[626 rows x 5 columns]

In [15]:
df_London.head()

,Hotel Name,Room Type,Single Bed,Double Bed,Price
0,Middle Eight - Preferred Hotels and Resorts,Urban Deluxe,No,Yes,"₹ 35,344"
1,The Carlton Tower Jumeirah,Superior Room with exclusive access to Cadogan...,No,No,"₹ 82,887"
2,Zedwell Greenwich,Double Room,No,Yes,"₹ 11,714"
3,"Maldron Hotel Finsbury Park, London",Deluxe Double Room,No,Yes,"₹ 17,167"
4,Zedwell Underground Tottenham Court Rd,Cocoon 2,No,Yes,"₹ 13,128"

                *************** Scrapping Data for City - Kuala Lumpur, Malaysia ********************

In [16]:
driver.get('https://www.booking.com/searchresults.en-gb.html?label=yho748jc-1FCAEoggI46AdIM1gDaGyIAQGYAQm4ARfIAQzYAQHoAQH4AQyIAgGoAgO4AurS96YGwAIB0gIkMTJhN2VkNjAtYzc1MS00MjVhLTg3ZjYtMzI5ZWMzNzlkNzhm2AIG4AIB&sid=b8f957b39c045a637fc32a3a001d95d0&aid=397646&checkin=2023-11-06&checkout=2023-11-07&city=-2403010&nflt=ht_id%3D204')

In [17]:
import pandas as pd


hotel_data = []

# Define the number of pages you want to scrape (5 in this case)
start_page = 1
end_page = 25

for page in range(start_page, end_page + 1):
    try:
        # Extract data using XPaths
        hotel_name_elements = driver.find_elements(By.XPATH, '//div[@class="f6431b446c a15b38c233"]')
        room_type_elements = driver.find_elements(By.XPATH, '//span[@class="e8f7c070a7"]')
        single_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        double_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        price_elements = driver.find_elements(By.XPATH, '//span[@class="f6431b446c fbfd7c1165 e84eb96b1f"]')
        
        num_elements = min(len(hotel_name_elements), len(room_type_elements), len(single_bed_elements), len(double_bed_elements), len(price_elements))
        
        for i in range(num_elements):
            hotel_name = hotel_name_elements[i].text
            room_type = room_type_elements[i].text if i < len(room_type_elements) else "N/A"
            
            # Check if the extracted text contains "single" and "double"
            single_bed_text = single_bed_elements[i].text if i < len(single_bed_elements) else "N/A"
            double_bed_text = double_bed_elements[i].text if i < len(double_bed_elements) else "N/A"
            
            single_bed = "Yes" if "single" in single_bed_text.lower() else "No"
            double_bed = "Yes" if "double" in double_bed_text.lower() else "No"
            
            price = price_elements[i].text if i < len(price_elements) else "N/A"

            # Store the data in a suitable data structure, e.g., a list of dictionaries
            hotel_data.append({
                "Hotel Name": hotel_name,
                "Room Type": room_type,
                "Single Bed": single_bed,
                "Double Bed": double_bed,
                "Price": price
            })
    except NoSuchElementException:
        # Handle the case when an element is not found
        hotel_data.append({
            "Hotel Name": "N/A",
            "Room Type": "N/A",
            "Single Bed": "N/A",
            "Double Bed": "N/A",
            "Price": "N/A"
        })
    
    try:
        # Click the "Next" button to navigate to the next page
        nxt_button = driver.find_element(By.XPATH, '//div[@class="b16a89683f cab1524053"]')
        nxt_button.click()
    except NoSuchElementException:
        # Handle the case when the "Next" button is not found
        print("Next button not found. Exiting the loop.")
        break
    
    # Add a short delay to allow the next page to load
    time.sleep(2)

# Create a DataFrame from the scraped data
df_Malaysia = pd.DataFrame(hotel_data)

# Print the DataFrame
print(df_Malaysia)

                                    Hotel Name  \
0                    Expressionz Suites by V&C
1                 ViiA Residences Kuala Lumpur
2                  OYO 90865 Hotel De Nice Inn
3    Millerz Square Mid Valley, Old Klang Road
4                    Astar Hotel Bukit Bintang
..                                         ...
620         Leo Leisure Hotel @ Central Market
621                                SunGold Inn
622                   12FLY Hotel Kuala Lumpur
623             OYO 89652 Bjorn Boutique Hotel
624                  YY318 Hotel Bukit Bintang

                               Room Type Single Bed Double Bed    Price
0                      Deluxe King Suite         No        Yes  ₹ 2,615
1                    Signature 1 Bedroom         No        Yes  ₹ 6,590
2                    Standard Queen Room         No        Yes  ₹ 1,370
3                       Studio Apartment        Yes        Yes  ₹ 1,925
4                    Standard Queen Room         No        Yes  ₹ 1,726
..                                   ...        ...        ...      ...
620                 Standard Tatami Room         No        Yes  ₹ 1,360
621                  Standard Queen Room         No        Yes  ₹ 2,103
622  Standard Double Room without Window         No        Yes  ₹ 2,929
623                   Deluxe Double Room         No        Yes  ₹ 1,822
624                  Standard Queen Room         No        Yes  ₹ 1,569

[625 rows x 5 columns]

In [18]:
df_Malaysia.head()

,Hotel Name,Room Type,Single Bed,Double Bed,Price
0,Expressionz Suites by V&C,Deluxe King Suite,No,Yes,"₹ 2,615"
1,ViiA Residences Kuala Lumpur,Signature 1 Bedroom,No,Yes,"₹ 6,590"
2,OYO 90865 Hotel De Nice Inn,Standard Queen Room,No,Yes,"₹ 1,370"
3,"Millerz Square Mid Valley, Old Klang Road",Studio Apartment,Yes,Yes,"₹ 1,925"
4,Astar Hotel Bukit Bintang,Standard Queen Room,No,Yes,"₹ 1,726"

            ********************** Webscraping for City - Manchester *******************

In [21]:
driver.get('https://www.booking.com/searchresults.en-gb.html?label=yho748jc-1FCAEoggI46AdIM1gDaGyIAQGYAQm4ARfIAQzYAQHoAQH4AQyIAgGoAgO4AurS96YGwAIB0gIkMTJhN2VkNjAtYzc1MS00MjVhLTg3ZjYtMzI5ZWMzNzlkNzhm2AIG4AIB&sid=b8f957b39c045a637fc32a3a001d95d0&aid=397646&ss=Manchester%2C+Greater+Manchester%2C+United+Kingdom&ssne=Kuala+Lumpur&ssne_untouched=Kuala+Lumpur&lang=en-gb&src=searchresults&dest_id=-2602512&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=en&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=d1a08c82272900f0&ac_meta=GhBkMWEwOGM4MjI3MjkwMGYwIAAoATICZW46BE1hbmNAAEoAUAA%3D&checkin=2023-11-06&checkout=2023-11-07&group_adults=2&no_rooms=1&group_children=0&nflt=ht_id%3D204')

In [22]:
import pandas as pd


hotel_data = []

# Define the number of pages you want to scrape (5 in this case)
start_page = 1
end_page = 25

for page in range(start_page, end_page + 1):
    try:
        # Extract data using XPaths
        hotel_name_elements = driver.find_elements(By.XPATH, '//div[@class="f6431b446c a15b38c233"]')
        room_type_elements = driver.find_elements(By.XPATH, '//span[@class="e8f7c070a7"]')
        single_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        double_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        price_elements = driver.find_elements(By.XPATH, '//span[@class="f6431b446c fbfd7c1165 e84eb96b1f"]')
        
        num_elements = min(len(hotel_name_elements), len(room_type_elements), len(single_bed_elements), len(double_bed_elements), len(price_elements))
        
        for i in range(num_elements):
            hotel_name = hotel_name_elements[i].text
            room_type = room_type_elements[i].text if i < len(room_type_elements) else "N/A"
            
            # Check if the extracted text contains "single" and "double"
            single_bed_text = single_bed_elements[i].text if i < len(single_bed_elements) else "N/A"
            double_bed_text = double_bed_elements[i].text if i < len(double_bed_elements) else "N/A"
            
            single_bed = "Yes" if "single" in single_bed_text.lower() else "No"
            double_bed = "Yes" if "double" in double_bed_text.lower() else "No"
            
            price = price_elements[i].text if i < len(price_elements) else "N/A"

            # Store the data in a suitable data structure, e.g., a list of dictionaries
            hotel_data.append({
                "Hotel Name": hotel_name,
                "Room Type": room_type,
                "Single Bed": single_bed,
                "Double Bed": double_bed,
                "Price": price
            })
    except NoSuchElementException:
        # Handle the case when an element is not found
        hotel_data.append({
            "Hotel Name": "N/A",
            "Room Type": "N/A",
            "Single Bed": "N/A",
            "Double Bed": "N/A",
            "Price": "N/A"
        })
    
    try:
        # Click the "Next" button to navigate to the next page
        nxt_button = driver.find_element(By.XPATH, '//div[@class="b16a89683f cab1524053"]')
        nxt_button.click()
    except NoSuchElementException:
        # Handle the case when the "Next" button is not found
        print("Next button not found. Exiting the loop.")
        break
    
    # Add a short delay to allow the next page to load
    time.sleep(2)

# Create a DataFrame from the scraped data
df_Manchester = pd.DataFrame(hotel_data)

# Print the DataFrame
print(df_Manchester)

Next button not found. Exiting the loop.
                                          Hotel Name  \
0                           The Townhouse Manchester
1       ibis Budget Manchester Centre Pollard Street
2    Residence Inn by Marriott Manchester Piccadilly
3          ibis Manchester Centre 96 Portland Street
4                                    Whitworth Locke
..                                               ...
114                               The Pleasant House
115                      BrewDog DogHouse Manchester
116                               The Pleasant House
117         Grade Ii Chaseley Mansion 1 King-bed Apt
118     Swan Street Townhouse Hot Tub & Roof Terrace

                          Room Type Single Bed Double Bed      Price
0                Standard Twin Room        Yes         No   ₹ 10,815
1    Classic Room with 1 double bed         No        Yes    ₹ 4,375
2                       Double Room         No        Yes    ₹ 9,593
3         Double Sweet Room by Ibis         No        Yes    ₹ 6,786
4                       City Studio         No        Yes   ₹ 11,209
..                              ...        ...        ...        ...
114                       Twin Room        Yes         No    ₹ 4,999
115   King Room - Disability Access         No        Yes   ₹ 26,559
116              Deluxe King Studio         No        Yes    ₹ 8,089
117              Superior Apartment         No        Yes    ₹ 9,190
118                       Apartment        Yes        Yes  ₹ 118,151

[119 rows x 5 columns]

In [23]:
df_Manchester.head()

,Hotel Name,Room Type,Single Bed,Double Bed,Price
0,The Townhouse Manchester,Standard Twin Room,Yes,No,"₹ 10,815"
1,ibis Budget Manchester Centre Pollard Street,Classic Room with 1 double bed,No,Yes,"₹ 4,375"
2,Residence Inn by Marriott Manchester Piccadilly,Double Room,No,Yes,"₹ 9,593"
3,ibis Manchester Centre 96 Portland Street,Double Sweet Room by Ibis,No,Yes,"₹ 6,786"
4,Whitworth Locke,City Studio,No,Yes,"₹ 11,209"

            ***************** Webscraping for City - New Delhi **********************

In [28]:
driver.get('https://www.booking.com/searchresults.en-gb.html?label=yho748jc-1FCAEoggI46AdIM1gDaGyIAQGYAQm4ARfIAQzYAQHoAQH4AQyIAgGoAgO4AurS96YGwAIB0gIkMTJhN2VkNjAtYzc1MS00MjVhLTg3ZjYtMzI5ZWMzNzlkNzhm2AIG4AIB&sid=b8f957b39c045a637fc32a3a001d95d0&aid=397646&ss=New+Delhi%2C+Delhi+NCR%2C+India&ssne=Manchester&ssne_untouched=Manchester&lang=en-gb&src=searchresults&dest_id=-2106102&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=en&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=1a528d3a941e01ee&ac_meta=GhAxYTUyOGQzYTk0MWUwMWVlIAAoATICZW46BE5ldyBAAEoAUAA%3D&checkin=2023-11-06&checkout=2023-11-07&group_adults=2&no_rooms=1&group_children=0&nflt=ht_id%3D204')

In [30]:
import pandas as pd


hotel_data = []

# Define the number of pages you want to scrape (5 in this case)
start_page = 1
end_page = 25

for page in range(start_page, end_page + 1):
    try:
        # Extract data using XPaths
        hotel_name_elements = driver.find_elements(By.XPATH, '//div[@class="f6431b446c a15b38c233"]')
        room_type_elements = driver.find_elements(By.XPATH, '//span[@class="e8f7c070a7"]')
        single_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        double_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        price_elements = driver.find_elements(By.XPATH, '//span[@class="f6431b446c fbfd7c1165 e84eb96b1f"]')
        
        num_elements = min(len(hotel_name_elements), len(room_type_elements), len(single_bed_elements), len(double_bed_elements), len(price_elements))
        
        for i in range(num_elements):
            hotel_name = hotel_name_elements[i].text
            room_type = room_type_elements[i].text if i < len(room_type_elements) else "N/A"
            
            # Check if the extracted text contains "single" and "double"
            single_bed_text = single_bed_elements[i].text if i < len(single_bed_elements) else "N/A"
            double_bed_text = double_bed_elements[i].text if i < len(double_bed_elements) else "N/A"
            
            single_bed = "Yes" if "single" in single_bed_text.lower() else "No"
            double_bed = "Yes" if "double" in double_bed_text.lower() else "No"
            
            price = price_elements[i].text if i < len(price_elements) else "N/A"

            # Store the data in a suitable data structure, e.g., a list of dictionaries
            hotel_data.append({
                "Hotel Name": hotel_name,
                "Room Type": room_type,
                "Single Bed": single_bed,
                "Double Bed": double_bed,
                "Price": price
            })
    except NoSuchElementException:
        # Handle the case when an element is not found
        hotel_data.append({
            "Hotel Name": "N/A",
            "Room Type": "N/A",
            "Single Bed": "N/A",
            "Double Bed": "N/A",
            "Price": "N/A"
        })
    
    try:
        # Click the "Next" button to navigate to the next page
        nxt_button = driver.find_element(By.XPATH, '//div[@class="b16a89683f cab1524053"]')
        nxt_button.click()
    except NoSuchElementException:
        # Handle the case when the "Next" button is not found
        print("Next button not found. Exiting the loop.")
        break
    
    # Add a short delay to allow the next page to load
    time.sleep(2)

# Create a DataFrame from the scraped data
df_Delhi = pd.DataFrame(hotel_data)

# Print the DataFrame
print(df_Delhi)

                                       Hotel Name             Room Type  \
0                 The Kiara Near To Delhi Airport           Deluxe Room
1    Hotel TEj Unit by Flypath Near Delhi Airport           Deluxe Room
2    Hotel Step-in Gold Near NSDL Railway Station    Deluxe Double Room
3           Hotel The Tark Near IGI Airport Delhi           Deluxe Room
4                    The Kiara Near Delhi Airport           Deluxe Room
..                                            ...                   ...
620                    Treebo Trend TMS Residency  Standard Double Room
621         Hotel Kuber internatational New Delhi  Standard Double Room
622                                  Hotel Le Roi    Deluxe Double Room
623                  OYO Flagship Hotel Royal Inn   Classic Triple Room
624                             hotel ankur plaza           Double Room

    Single Bed Double Bed    Price
0           No        Yes  ₹ 1,710
1           No        Yes  ₹ 2,275
2           No        Yes  ₹ 1,079
3           No        Yes  ₹ 1,548
4           No        Yes  ₹ 1,874
..         ...        ...      ...
620         No        Yes  ₹ 2,523
621        Yes         No  ₹ 1,715
622         No        Yes  ₹ 2,634
623         No        Yes  ₹ 1,082
624         No        Yes  ₹ 1,750

[625 rows x 5 columns]

In [31]:
df_Delhi.head()

,Hotel Name,Room Type,Single Bed,Double Bed,Price
0,The Kiara Near To Delhi Airport,Deluxe Room,No,Yes,"₹ 1,710"
1,Hotel TEj Unit by Flypath Near Delhi Airport,Deluxe Room,No,Yes,"₹ 2,275"
2,Hotel Step-in Gold Near NSDL Railway Station,Deluxe Double Room,No,Yes,"₹ 1,079"
3,Hotel The Tark Near IGI Airport Delhi,Deluxe Room,No,Yes,"₹ 1,548"
4,The Kiara Near Delhi Airport,Deluxe Room,No,Yes,"₹ 1,874"

                ****************** Webscraping for City - Birmingham ***************************

In [32]:
driver.get('https://www.booking.com/searchresults.en-gb.html?label=yho748jc-1FCAEoggI46AdIM1gDaGyIAQGYAQm4ARfIAQzYAQHoAQH4AQyIAgGoAgO4AurS96YGwAIB0gIkMTJhN2VkNjAtYzc1MS00MjVhLTg3ZjYtMzI5ZWMzNzlkNzhm2AIG4AIB&sid=b8f957b39c045a637fc32a3a001d95d0&aid=397646&ss=Birmingham%2C+West+Midlands%2C+United+Kingdom&ssne=New+Delhi&ssne_untouched=New+Delhi&lang=en-gb&src=searchresults&dest_id=-2589989&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=en&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=0ecb8d8bce020470&ac_meta=GhAwZWNiOGQ4YmNlMDIwNDcwIAAoATICZW46A0JpckAASgBQAA%3D%3D&checkin=2023-11-06&checkout=2023-11-07&group_adults=2&no_rooms=1&group_children=0&nflt=ht_id%3D204')

In [33]:
import pandas as pd


hotel_data = []

# Define the number of pages you want to scrape (5 in this case)
start_page = 1
end_page = 25

for page in range(start_page, end_page + 1):
    try:
        # Extract data using XPaths
        hotel_name_elements = driver.find_elements(By.XPATH, '//div[@class="f6431b446c a15b38c233"]')
        room_type_elements = driver.find_elements(By.XPATH, '//span[@class="e8f7c070a7"]')
        single_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        double_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        price_elements = driver.find_elements(By.XPATH, '//span[@class="f6431b446c fbfd7c1165 e84eb96b1f"]')
        
        num_elements = min(len(hotel_name_elements), len(room_type_elements), len(single_bed_elements), len(double_bed_elements), len(price_elements))
        
        for i in range(num_elements):
            hotel_name = hotel_name_elements[i].text
            room_type = room_type_elements[i].text if i < len(room_type_elements) else "N/A"
            
            # Check if the extracted text contains "single" and "double"
            single_bed_text = single_bed_elements[i].text if i < len(single_bed_elements) else "N/A"
            double_bed_text = double_bed_elements[i].text if i < len(double_bed_elements) else "N/A"
            
            single_bed = "Yes" if "single" in single_bed_text.lower() else "No"
            double_bed = "Yes" if "double" in double_bed_text.lower() else "No"
            
            price = price_elements[i].text if i < len(price_elements) else "N/A"

            # Store the data in a suitable data structure, e.g., a list of dictionaries
            hotel_data.append({
                "Hotel Name": hotel_name,
                "Room Type": room_type,
                "Single Bed": single_bed,
                "Double Bed": double_bed,
                "Price": price
            })
    except NoSuchElementException:
        # Handle the case when an element is not found
        hotel_data.append({
            "Hotel Name": "N/A",
            "Room Type": "N/A",
            "Single Bed": "N/A",
            "Double Bed": "N/A",
            "Price": "N/A"
        })
    
    try:
        # Click the "Next" button to navigate to the next page
        nxt_button = driver.find_element(By.XPATH, '//div[@class="b16a89683f cab1524053"]')
        nxt_button.click()
    except NoSuchElementException:
        # Handle the case when the "Next" button is not found
        print("Next button not found. Exiting the loop.")
        break
    
    # Add a short delay to allow the next page to load
    time.sleep(2)

# Create a DataFrame from the scraped data
df_Birmingham = pd.DataFrame(hotel_data)

# Print the DataFrame
print(df_Birmingham)

Next button not found. Exiting the loop.
                                           Hotel Name  \
0                        Campanile Hotel - Birmingham
1   Birmingham Strathallan Hotel, BW Signature Col...
2   Castle Bromwich Hall; Sure Hotel Collection by...
3                           Aloft Birmingham Eastside
4            Aparthotel Adagio Birmingham City Centre
..                                                ...
72                                       Hagley Hotel
73                     Hotel 5 Ravenhurst Drive M6 J7
74                               Clover Spa and Hotel
75                                     Tri-Star Hotel
76                             The Loft at York House

                            Room Type Single Bed Double Bed     Price
0                           Twin Room        Yes         No   ₹ 8,382
1       Cozy Double Room- Non Smoking         No        Yes   ₹ 5,235
2              Accessible Double Room         No        Yes   ₹ 6,726
3           Aloft, Guest room, 1 King         No        Yes   ₹ 9,391
4              Studio with Double Bed         No        Yes   ₹ 9,997
..                                ...        ...        ...       ...
72                        Double Room         No        Yes   ₹ 5,554
73                 Budget Double Room         No        Yes   ₹ 7,362
74                  Small Double Room         No        Yes  ₹ 14,138
75  Double Room with Private Bathroom         No        Yes  ₹ 16,056
76                          Apartment         No        Yes  ₹ 10,906

[77 rows x 5 columns]

In [35]:
df_Birmingham.head()

,Hotel Name,Room Type,Single Bed,Double Bed,Price
0,Campanile Hotel - Birmingham,Twin Room,Yes,No,"₹ 8,382"
1,"Birmingham Strathallan Hotel, BW Signature Col...",Cozy Double Room- Non Smoking,No,Yes,"₹ 5,235"
2,Castle Bromwich Hall; Sure Hotel Collection by...,Accessible Double Room,No,Yes,"₹ 6,726"
3,Aloft Birmingham Eastside,"Aloft, Guest room, 1 King",No,Yes,"₹ 9,391"
4,Aparthotel Adagio Birmingham City Centre,Studio with Double Bed,No,Yes,"₹ 9,997"

            ************************ Webscraping for city - Berlin ********************

In [36]:
driver.get('https://www.booking.com/searchresults.en-gb.html?label=yho748jc-1FCAEoggI46AdIM1gDaGyIAQGYAQm4ARfIAQzYAQHoAQH4AQyIAgGoAgO4AurS96YGwAIB0gIkMTJhN2VkNjAtYzc1MS00MjVhLTg3ZjYtMzI5ZWMzNzlkNzhm2AIG4AIB&sid=b8f957b39c045a637fc32a3a001d95d0&aid=397646&ss=Berlin%2C+Berlin+Federal+State%2C+Germany&ssne=Birmingham&ssne_untouched=Birmingham&lang=en-gb&src=searchresults&dest_id=-1746443&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=en&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=8e788e9ff13c010f&ac_meta=GhA4ZTc4OGU5ZmYxM2MwMTBmIAAoATICZW46A0JlckAASgBQAA%3D%3D&checkin=2023-11-06&checkout=2023-11-07&group_adults=2&no_rooms=1&group_children=0&nflt=ht_id%3D204')

In [37]:
import pandas as pd


hotel_data = []

# Define the number of pages you want to scrape (5 in this case)
start_page = 1
end_page = 25

for page in range(start_page, end_page + 1):
    try:
        # Extract data using XPaths
        hotel_name_elements = driver.find_elements(By.XPATH, '//div[@class="f6431b446c a15b38c233"]')
        room_type_elements = driver.find_elements(By.XPATH, '//span[@class="e8f7c070a7"]')
        single_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        double_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        price_elements = driver.find_elements(By.XPATH, '//span[@class="f6431b446c fbfd7c1165 e84eb96b1f"]')
        
        num_elements = min(len(hotel_name_elements), len(room_type_elements), len(single_bed_elements), len(double_bed_elements), len(price_elements))
        
        for i in range(num_elements):
            hotel_name = hotel_name_elements[i].text
            room_type = room_type_elements[i].text if i < len(room_type_elements) else "N/A"
            
            # Check if the extracted text contains "single" and "double"
            single_bed_text = single_bed_elements[i].text if i < len(single_bed_elements) else "N/A"
            double_bed_text = double_bed_elements[i].text if i < len(double_bed_elements) else "N/A"
            
            single_bed = "Yes" if "single" in single_bed_text.lower() else "No"
            double_bed = "Yes" if "double" in double_bed_text.lower() else "No"
            
            price = price_elements[i].text if i < len(price_elements) else "N/A"

            # Store the data in a suitable data structure, e.g., a list of dictionaries
            hotel_data.append({
                "Hotel Name": hotel_name,
                "Room Type": room_type,
                "Single Bed": single_bed,
                "Double Bed": double_bed,
                "Price": price
            })
    except NoSuchElementException:
        # Handle the case when an element is not found
        hotel_data.append({
            "Hotel Name": "N/A",
            "Room Type": "N/A",
            "Single Bed": "N/A",
            "Double Bed": "N/A",
            "Price": "N/A"
        })
    
    try:
        # Click the "Next" button to navigate to the next page
        nxt_button = driver.find_element(By.XPATH, '//div[@class="b16a89683f cab1524053"]')
        nxt_button.click()
    except NoSuchElementException:
        # Handle the case when the "Next" button is not found
        print("Next button not found. Exiting the loop.")
        break
    
    # Add a short delay to allow the next page to load
    time.sleep(2)

# Create a DataFrame from the scraped data
df_Berlin = pd.DataFrame(hotel_data)

# Print the DataFrame
print(df_Berlin)

Next button not found. Exiting the loop.
                                            Hotel Name  \
0                        Scandic Berlin Kurfürstendamm
1            Hotel am Steinplatz, Autograph Collection
2                  DoubleTree by Hilton Berlin Ku'damm
3                           Premier Inn Berlin Airport
4                            B&B Hotel Berlin City-Ost
..                                                 ...
440       Mondrian Suites Berlin am Checkpoint Charlie
441                                    Hotel Forsthaus
442  Schulz Hotel Berlin Wall at the East Side Gallery
443                                    Hotel Goldmarie
444                              Hotel zum Ziehbrunnen

                             Room Type Single Bed Double Bed     Price
0                 Standard Double Room        Yes        Yes  ₹ 10,385
1                  Deluxe Room, 2 Twin        Yes         No  ₹ 27,371
2                      King Guest Room         No        Yes  ₹ 13,603
3                 Standard Double Room         No        Yes   ₹ 5,721
4                            Twin Room        Yes         No   ₹ 6,513
..                                 ...        ...        ...       ...
440                     Premium Studio         No        Yes  ₹ 15,934
441                Double or Twin Room         No         No  ₹ 10,209
442                  Small Single Room        Yes         No  ₹ 36,800
443  Single Room with Private Bathroom        Yes         No  ₹ 16,554
444                        Single Room        Yes         No  ₹ 12,321

[445 rows x 5 columns]

In [38]:
df_Berlin.head()

,Hotel Name,Room Type,Single Bed,Double Bed,Price
0,Scandic Berlin Kurfürstendamm,Standard Double Room,Yes,Yes,"₹ 10,385"
1,"Hotel am Steinplatz, Autograph Collection","Deluxe Room, 2 Twin",Yes,No,"₹ 27,371"
2,DoubleTree by Hilton Berlin Ku'damm,King Guest Room,No,Yes,"₹ 13,603"
3,Premier Inn Berlin Airport,Standard Double Room,No,Yes,"₹ 5,721"
4,B&B Hotel Berlin City-Ost,Twin Room,Yes,No,"₹ 6,513"

            ********************** Webscraping for City - Sydney ***********************

In [39]:
driver.get('https://www.booking.com/searchresults.en-gb.html?label=yho748jc-1FCAEoggI46AdIM1gDaGyIAQGYAQm4ARfIAQzYAQHoAQH4AQyIAgGoAgO4AurS96YGwAIB0gIkMTJhN2VkNjAtYzc1MS00MjVhLTg3ZjYtMzI5ZWMzNzlkNzhm2AIG4AIB&sid=b8f957b39c045a637fc32a3a001d95d0&aid=397646&ss=Sydney&ssne=Sydney&ssne_untouched=Sydney&lang=en-gb&src=searchresults&dest_id=-1603135&dest_type=city&checkin=2023-11-06&checkout=2023-11-07&group_adults=2&no_rooms=1&group_children=0&nflt=ht_id%3D204')

In [40]:
import pandas as pd


hotel_data = []

# Define the number of pages you want to scrape (5 in this case)
start_page = 1
end_page = 25

for page in range(start_page, end_page + 1):
    try:
        # Extract data using XPaths
        hotel_name_elements = driver.find_elements(By.XPATH, '//div[@class="f6431b446c a15b38c233"]')
        room_type_elements = driver.find_elements(By.XPATH, '//span[@class="e8f7c070a7"]')
        single_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        double_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        price_elements = driver.find_elements(By.XPATH, '//span[@class="f6431b446c fbfd7c1165 e84eb96b1f"]')
        
        num_elements = min(len(hotel_name_elements), len(room_type_elements), len(single_bed_elements), len(double_bed_elements), len(price_elements))
        
        for i in range(num_elements):
            hotel_name = hotel_name_elements[i].text
            room_type = room_type_elements[i].text if i < len(room_type_elements) else "N/A"
            
            # Check if the extracted text contains "single" and "double"
            single_bed_text = single_bed_elements[i].text if i < len(single_bed_elements) else "N/A"
            double_bed_text = double_bed_elements[i].text if i < len(double_bed_elements) else "N/A"
            
            single_bed = "Yes" if "single" in single_bed_text.lower() else "No"
            double_bed = "Yes" if "double" in double_bed_text.lower() else "No"
            
            price = price_elements[i].text if i < len(price_elements) else "N/A"

            # Store the data in a suitable data structure, e.g., a list of dictionaries
            hotel_data.append({
                "Hotel Name": hotel_name,
                "Room Type": room_type,
                "Single Bed": single_bed,
                "Double Bed": double_bed,
                "Price": price
            })
    except NoSuchElementException:
        # Handle the case when an element is not found
        hotel_data.append({
            "Hotel Name": "N/A",
            "Room Type": "N/A",
            "Single Bed": "N/A",
            "Double Bed": "N/A",
            "Price": "N/A"
        })
    
    try:
        # Click the "Next" button to navigate to the next page
        nxt_button = driver.find_element(By.XPATH, '//div[@class="b16a89683f cab1524053"]')
        nxt_button.click()
    except NoSuchElementException:
        # Handle the case when the "Next" button is not found
        print("Next button not found. Exiting the loop.")
        break
    
    # Add a short delay to allow the next page to load
    time.sleep(2)

# Create a DataFrame from the scraped data
df_Sydney = pd.DataFrame(hotel_data)

# Print the DataFrame
print(df_Sydney)

Next button not found. Exiting the loop.
                                            Hotel Name  \
0                                  ibis Sydney Airport
1                                             W Sydney
2                             CKS Sydney Airport Hotel
3                    Metro Hotel Marlow Sydney Central
4                      Travelodge Hotel Sydney Airport
..                                                 ...
296                                  Park Hyatt Sydney
297                                         The Bercin
298  Hotel Style Monterey Guest Studio near Hospita...
299  VENUS Harbourside - FEMALE ONLY HOSTEL - Long ...
300  VENUS Surry Hills - FEMALE ONLY HOSTEL - Long ...

                                             Room Type Single Bed Double Bed  \
0                                 Standard Double Room         No        Yes
1                   Wonderful King Room with City View         No        Yes
2                                  Standard Queen Room         No        Yes
3                                   Deluxe Double Room         No        Yes
4                                           Queen Room         No        Yes
..                                                 ...        ...        ...
296                        King Room with Harbour View         No        Yes
297                                          Apartment        Yes        Yes
298                            Studio with Garden View         No        Yes
299                 Bed in 4-Bed Female Dormitory Room         No         No
300  Bunk Bed in a 2 beds FEMALE room w/ensuite bat...         No         No

        Price
0     ₹ 9,088
1    ₹ 31,468
2     ₹ 7,985
3    ₹ 10,366
4     ₹ 9,603
..        ...
296  ₹ 67,769
297  ₹ 56,264
298   ₹ 9,982
299   ₹ 5,196
300   ₹ 5,196

[301 rows x 5 columns]

                     ********************* Webscraping for City - Melbourne **********************

In [41]:
driver.get('https://www.booking.com/searchresults.en-gb.html?label=yho748jc-1FCAEoggI46AdIM1gDaGyIAQGYAQm4ARfIAQzYAQHoAQH4AQyIAgGoAgO4AurS96YGwAIB0gIkMTJhN2VkNjAtYzc1MS00MjVhLTg3ZjYtMzI5ZWMzNzlkNzhm2AIG4AIB&sid=b8f957b39c045a637fc32a3a001d95d0&aid=397646&ss=Melbourne%2C+Victoria%2C+Australia&ssne=Sydney&ssne_untouched=Sydney&lang=en-gb&src=searchresults&dest_id=-1586844&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=en&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=8f4d8fad69af0228&ac_meta=GhA4ZjRkOGZhZDY5YWYwMjI4IAAoATICZW46Bk1lbGJvdUAASgBQAA%3D%3D&checkin=2023-11-06&checkout=2023-11-07&group_adults=2&no_rooms=1&group_children=0&nflt=ht_id%3D204')

In [42]:
import pandas as pd


hotel_data = []

# Define the number of pages you want to scrape (5 in this case)
start_page = 1
end_page = 25

for page in range(start_page, end_page + 1):
    try:
        # Extract data using XPaths
        hotel_name_elements = driver.find_elements(By.XPATH, '//div[@class="f6431b446c a15b38c233"]')
        room_type_elements = driver.find_elements(By.XPATH, '//span[@class="e8f7c070a7"]')
        single_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        double_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        price_elements = driver.find_elements(By.XPATH, '//span[@class="f6431b446c fbfd7c1165 e84eb96b1f"]')
        
        num_elements = min(len(hotel_name_elements), len(room_type_elements), len(single_bed_elements), len(double_bed_elements), len(price_elements))
        
        for i in range(num_elements):
            hotel_name = hotel_name_elements[i].text
            room_type = room_type_elements[i].text if i < len(room_type_elements) else "N/A"
            
            # Check if the extracted text contains "single" and "double"
            single_bed_text = single_bed_elements[i].text if i < len(single_bed_elements) else "N/A"
            double_bed_text = double_bed_elements[i].text if i < len(double_bed_elements) else "N/A"
            
            single_bed = "Yes" if "single" in single_bed_text.lower() else "No"
            double_bed = "Yes" if "double" in double_bed_text.lower() else "No"
            
            price = price_elements[i].text if i < len(price_elements) else "N/A"

            # Store the data in a suitable data structure, e.g., a list of dictionaries
            hotel_data.append({
                "Hotel Name": hotel_name,
                "Room Type": room_type,
                "Single Bed": single_bed,
                "Double Bed": double_bed,
                "Price": price
            })
    except NoSuchElementException:
        # Handle the case when an element is not found
        hotel_data.append({
            "Hotel Name": "N/A",
            "Room Type": "N/A",
            "Single Bed": "N/A",
            "Double Bed": "N/A",
            "Price": "N/A"
        })
    
    try:
        # Click the "Next" button to navigate to the next page
        nxt_button = driver.find_element(By.XPATH, '//div[@class="b16a89683f cab1524053"]')
        nxt_button.click()
    except NoSuchElementException:
        # Handle the case when the "Next" button is not found
        print("Next button not found. Exiting the loop.")
        break
    
    # Add a short delay to allow the next page to load
    time.sleep(2)

# Create a DataFrame from the scraped data
df_Melbourne = pd.DataFrame(hotel_data)

# Print the DataFrame
print(df_Melbourne)

Next button not found. Exiting the loop.
                                Hotel Name  \
0                         Nesuto Docklands
1                              Naima Hotel
2                        Dorsett Melbourne
3                   ibis Melbourne Central
4                       Causeway 353 Hotel
..                                     ...
246                         ACD Apartments
247  Melbourne CBD Central Apartment Hotel
248             Milano Serviced Apartments
249                         Highlander INN
250    Crest On Barkly Serviced Apartments

                                             Room Type Single Bed Double Bed  \
0                                    Premium Apartment         No        Yes
1    Studio with Balcony and Kitchen - Twin bedding...         No        Yes
2                                         Dorsett King         No        Yes
3                                  Compact Double Room         No        Yes
4                                     Deluxe King Room         No        Yes
..                                                 ...        ...        ...
246      Executive Two-Bedroom, Two-Bathroom Apartment         No        Yes
247                     Standard One-Bedroom Apartment         No        Yes
248                       Deluxe Two-Bedroom Apartment        Yes        Yes
249                              One-Bedroom Apartment         No        Yes
250                     Standard One-Bedroom Apartment         No        Yes

        Price
0     ₹ 9,745
1     ₹ 6,691
2     ₹ 7,943
3     ₹ 8,878
4    ₹ 12,009
..        ...
246  ₹ 25,164
247  ₹ 13,723
248  ₹ 17,458
249  ₹ 12,188
250   ₹ 9,732

[251 rows x 5 columns]

             ***************************** Webscraping for City - Paris ***************************

In [43]:
driver.get('https://www.booking.com/searchresults.en-gb.html?label=yho748jc-1FCAEoggI46AdIM1gDaGyIAQGYAQm4ARfIAQzYAQHoAQH4AQyIAgGoAgO4AurS96YGwAIB0gIkMTJhN2VkNjAtYzc1MS00MjVhLTg3ZjYtMzI5ZWMzNzlkNzhm2AIG4AIB&sid=b8f957b39c045a637fc32a3a001d95d0&aid=397646&ss=Paris%2C+Ile+de+France%2C+France&ssne=Melbourne&ssne_untouched=Melbourne&lang=en-gb&src=searchresults&dest_id=-1456928&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=en&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=c0b5900266ab00d1&ac_meta=GhBjMGI1OTAwMjY2YWIwMGQxIAAoATICZW46BVBhcmlzQABKAFAA&checkin=2023-11-06&checkout=2023-11-07&group_adults=2&no_rooms=1&group_children=0&nflt=ht_id%3D204')

In [44]:
import pandas as pd


hotel_data = []

# Define the number of pages you want to scrape (5 in this case)
start_page = 1
end_page = 25

for page in range(start_page, end_page + 1):
    try:
        # Extract data using XPaths
        hotel_name_elements = driver.find_elements(By.XPATH, '//div[@class="f6431b446c a15b38c233"]')
        room_type_elements = driver.find_elements(By.XPATH, '//span[@class="e8f7c070a7"]')
        single_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        double_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        price_elements = driver.find_elements(By.XPATH, '//span[@class="f6431b446c fbfd7c1165 e84eb96b1f"]')
        
        num_elements = min(len(hotel_name_elements), len(room_type_elements), len(single_bed_elements), len(double_bed_elements), len(price_elements))
        
        for i in range(num_elements):
            hotel_name = hotel_name_elements[i].text
            room_type = room_type_elements[i].text if i < len(room_type_elements) else "N/A"
            
            # Check if the extracted text contains "single" and "double"
            single_bed_text = single_bed_elements[i].text if i < len(single_bed_elements) else "N/A"
            double_bed_text = double_bed_elements[i].text if i < len(double_bed_elements) else "N/A"
            
            single_bed = "Yes" if "single" in single_bed_text.lower() else "No"
            double_bed = "Yes" if "double" in double_bed_text.lower() else "No"
            
            price = price_elements[i].text if i < len(price_elements) else "N/A"

            # Store the data in a suitable data structure, e.g., a list of dictionaries
            hotel_data.append({
                "Hotel Name": hotel_name,
                "Room Type": room_type,
                "Single Bed": single_bed,
                "Double Bed": double_bed,
                "Price": price
            })
    except NoSuchElementException:
        # Handle the case when an element is not found
        hotel_data.append({
            "Hotel Name": "N/A",
            "Room Type": "N/A",
            "Single Bed": "N/A",
            "Double Bed": "N/A",
            "Price": "N/A"
        })
    
    try:
        # Click the "Next" button to navigate to the next page
        nxt_button = driver.find_element(By.XPATH, '//div[@class="b16a89683f cab1524053"]')
        nxt_button.click()
    except NoSuchElementException:
        # Handle the case when the "Next" button is not found
        print("Next button not found. Exiting the loop.")
        break
    
    # Add a short delay to allow the next page to load
    time.sleep(2)

# Create a DataFrame from the scraped data
df_Paris = pd.DataFrame(hotel_data)

# Print the DataFrame
print(df_Paris)

                                        Hotel Name  \
0                       Hôtel Saint-André des Arts
1                                 Sonder Quintinie
2                                     Hôtel Lucien
3    Holiday Inn Paris Gare de l'Est, an IHG Hotel
4                                       Hotel Anya
..                                             ...
621                  First Hotel Paris Tour Eiffel
622                      Citadines Trocadéro Paris
623               ibis Paris Avenue d'Italie 13ème
624                     Hôtel Saint-André des Arts
625                                   Hôtel Piapia

                                             Room Type Single Bed Double Bed  \
0    Deluxe Double or Twin Room - Access to Wellnes...        Yes        Yes
1                                               Studio         No        Yes
2                                          Double Room         No        Yes
3                            Double Room - Non-Smoking         No        Yes
4                                          Double Room         No        Yes
..                                                 ...        ...        ...
621                                Classic Double Room        Yes        Yes
622                                             Studio         No        Yes
623                               Standard Double Room         No        Yes
624  Deluxe Double or Twin Room - Access to Wellnes...        Yes        Yes
625                       Superior Double or Twin Room        Yes        Yes

        Price
0    ₹ 30,618
1    ₹ 14,610
2    ₹ 15,921
3    ₹ 10,218
4     ₹ 8,361
..        ...
621  ₹ 20,506
622  ₹ 17,426
623  ₹ 10,646
624  ₹ 30,618
625   ₹ 9,653

[626 rows x 5 columns]

            ************************** Webscraping for City - Tokyo ****************************

In [45]:
driver.get('https://www.booking.com/searchresults.en-gb.html?label=yho748jc-1FCAEoggI46AdIM1gDaGyIAQGYAQm4ARfIAQzYAQHoAQH4AQyIAgGoAgO4AurS96YGwAIB0gIkMTJhN2VkNjAtYzc1MS00MjVhLTg3ZjYtMzI5ZWMzNzlkNzhm2AIG4AIB&sid=b8f957b39c045a637fc32a3a001d95d0&aid=397646&ss=Tokyo%2C+Tokyo-to%2C+Japan&ssne=Paris&ssne_untouched=Paris&lang=en-gb&src=searchresults&dest_id=-246227&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=en&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=aac29059b6ec0010&ac_meta=GhBhYWMyOTA1OWI2ZWMwMDEwIAAoATICZW46A1Rva0AASgBQAA%3D%3D&checkin=2023-11-06&checkout=2023-11-07&group_adults=2&no_rooms=1&group_children=0&nflt=ht_id%3D204')

In [46]:
import pandas as pd


hotel_data = []

# Define the number of pages you want to scrape (5 in this case)
start_page = 1
end_page = 25

for page in range(start_page, end_page + 1):
    try:
        # Extract data using XPaths
        hotel_name_elements = driver.find_elements(By.XPATH, '//div[@class="f6431b446c a15b38c233"]')
        room_type_elements = driver.find_elements(By.XPATH, '//span[@class="e8f7c070a7"]')
        single_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        double_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        price_elements = driver.find_elements(By.XPATH, '//span[@class="f6431b446c fbfd7c1165 e84eb96b1f"]')
        
        num_elements = min(len(hotel_name_elements), len(room_type_elements), len(single_bed_elements), len(double_bed_elements), len(price_elements))
        
        for i in range(num_elements):
            hotel_name = hotel_name_elements[i].text
            room_type = room_type_elements[i].text if i < len(room_type_elements) else "N/A"
            
            # Check if the extracted text contains "single" and "double"
            single_bed_text = single_bed_elements[i].text if i < len(single_bed_elements) else "N/A"
            double_bed_text = double_bed_elements[i].text if i < len(double_bed_elements) else "N/A"
            
            single_bed = "Yes" if "single" in single_bed_text.lower() else "No"
            double_bed = "Yes" if "double" in double_bed_text.lower() else "No"
            
            price = price_elements[i].text if i < len(price_elements) else "N/A"

            # Store the data in a suitable data structure, e.g., a list of dictionaries
            hotel_data.append({
                "Hotel Name": hotel_name,
                "Room Type": room_type,
                "Single Bed": single_bed,
                "Double Bed": double_bed,
                "Price": price
            })
    except NoSuchElementException:
        # Handle the case when an element is not found
        hotel_data.append({
            "Hotel Name": "N/A",
            "Room Type": "N/A",
            "Single Bed": "N/A",
            "Double Bed": "N/A",
            "Price": "N/A"
        })
    
    try:
        # Click the "Next" button to navigate to the next page
        nxt_button = driver.find_element(By.XPATH, '//div[@class="b16a89683f cab1524053"]')
        nxt_button.click()
    except NoSuchElementException:
        # Handle the case when the "Next" button is not found
        print("Next button not found. Exiting the loop.")
        break
    
    # Add a short delay to allow the next page to load
    time.sleep(2)

# Create a DataFrame from the scraped data
df_Tokyo = pd.DataFrame(hotel_data)

# Print the DataFrame
print(df_Tokyo)

                         Hotel Name  \
0        Tosei Hotel Cocone Asakusa
1    LOISIR HOTEL SHINAGAWA SEASIDE
2        Comfort Inn Tokyo Roppongi
3       Hotel JAL City Haneda Tokyo
4        Henn na Hotel Tokyo Haneda
..                              ...
619               Rhodes Kagurazaka
620        秋の旅館 秋叶原 Tokyo Akihabara
621                      Asta Hotel
622                The Westin Tokyo
623       Hotel Trend Asakusa Annex

                                             Room Type Single Bed Double Bed  \
0                            Room Selected at Check-In         No         No
1                                Double Room - Smoking         No        Yes
2                            Double Room - Non-Smoking         No        Yes
3                     【Prime Floor】Comfort Double Room         No        Yes
4    Double Room with Small Double Bed - (LG Styler...         No        Yes
..                                                 ...        ...        ...
619                                        Double Room         No        Yes
620                  Double Room with Private Bathroom         No        Yes
621                                        Double Room         No        Yes
622                   Double Room with Two Double Beds         No        Yes
623                          Double Room - Non-Smoking         No        Yes

        Price
0     ₹ 6,488
1     ₹ 6,100
2     ₹ 9,585
3     ₹ 8,130
4     ₹ 6,038
..        ...
619   ₹ 5,434
620   ₹ 4,991
621   ₹ 8,560
622  ₹ 50,626
623   ₹ 6,321

[624 rows x 5 columns]

                ************************** Webscraping for City - Toronto **********************

In [47]:
driver.get('https://www.booking.com/searchresults.en-gb.html?label=yho748jc-1FCAEoggI46AdIM1gDaGyIAQGYAQm4ARfIAQzYAQHoAQH4AQyIAgGoAgO4AurS96YGwAIB0gIkMTJhN2VkNjAtYzc1MS00MjVhLTg3ZjYtMzI5ZWMzNzlkNzhm2AIG4AIB&sid=b8f957b39c045a637fc32a3a001d95d0&aid=397646&ss=Toronto%2C+Ontario%2C+Canada&ssne=Tokyo&ssne_untouched=Tokyo&lang=en-gb&src=searchresults&dest_id=-574890&dest_type=city&ac_position=0&ac_click_type=b&ac_langcode=en&ac_suggestion_list_length=5&search_selected=true&search_pageview_id=8fa5907f4de80245&ac_meta=GhA4ZmE1OTA3ZjRkZTgwMjQ1IAAoATICZW46BVRvcm9uQABKAFAA&checkin=2023-11-06&checkout=2023-11-07&group_adults=2&no_rooms=1&group_children=0&nflt=ht_id%3D204')

In [48]:
import pandas as pd


hotel_data = []

# Define the number of pages you want to scrape (5 in this case)
start_page = 1
end_page = 25

for page in range(start_page, end_page + 1):
    try:
        # Extract data using XPaths
        hotel_name_elements = driver.find_elements(By.XPATH, '//div[@class="f6431b446c a15b38c233"]')
        room_type_elements = driver.find_elements(By.XPATH, '//span[@class="e8f7c070a7"]')
        single_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        double_bed_elements = driver.find_elements(By.XPATH, '//div[@class="fc367255e6"]')
        price_elements = driver.find_elements(By.XPATH, '//span[@class="f6431b446c fbfd7c1165 e84eb96b1f"]')
        
        num_elements = min(len(hotel_name_elements), len(room_type_elements), len(single_bed_elements), len(double_bed_elements), len(price_elements))
        
        for i in range(num_elements):
            hotel_name = hotel_name_elements[i].text
            room_type = room_type_elements[i].text if i < len(room_type_elements) else "N/A"
            
            # Check if the extracted text contains "single" and "double"
            single_bed_text = single_bed_elements[i].text if i < len(single_bed_elements) else "N/A"
            double_bed_text = double_bed_elements[i].text if i < len(double_bed_elements) else "N/A"
            
            single_bed = "Yes" if "single" in single_bed_text.lower() else "No"
            double_bed = "Yes" if "double" in double_bed_text.lower() else "No"
            
            price = price_elements[i].text if i < len(price_elements) else "N/A"

            # Store the data in a suitable data structure, e.g., a list of dictionaries
            hotel_data.append({
                "Hotel Name": hotel_name,
                "Room Type": room_type,
                "Single Bed": single_bed,
                "Double Bed": double_bed,
                "Price": price
            })
    except NoSuchElementException:
        # Handle the case when an element is not found
        hotel_data.append({
            "Hotel Name": "N/A",
            "Room Type": "N/A",
            "Single Bed": "N/A",
            "Double Bed": "N/A",
            "Price": "N/A"
        })
    
    try:
        # Click the "Next" button to navigate to the next page
        nxt_button = driver.find_element(By.XPATH, '//div[@class="b16a89683f cab1524053"]')
        nxt_button.click()
    except NoSuchElementException:
        # Handle the case when the "Next" button is not found
        print("Next button not found. Exiting the loop.")
        break
    
    # Add a short delay to allow the next page to load
    time.sleep(2)

# Create a DataFrame from the scraped data
df_Toronto = pd.DataFrame(hotel_data)

# Print the DataFrame
print(df_Toronto)

Next button not found. Exiting the loop.
                                            Hotel Name  \
0                                         The Fairview
1                                            W Toronto
2                DoubleTree by Hilton Toronto Downtown
3    Holiday Inn Express Toronto-North York, an IHG...
4    Holiday Inn Toronto Downtown Centre, an IHG Hotel
..                                                 ...
104                                   Casa Queen Hotel
105                  Yonge Suites Furnished Apartments
106                 Le Germain Hotel Maple Leaf Square
107                              The St. Regis Toronto
108                          The Ritz-Carlton, Toronto

                                             Room Type Single Bed Double Bed  \
0                               King Room with Balcony         No        Yes
1        Wonderful, Guest room, 1 King, Courtyard view         No        Yes
2                                            King Room         No        Yes
3              Standard Queen Room with Two Queen Beds         No        Yes
4                       Queen Room - Disability Access         No        Yes
..                                                 ...        ...        ...
104                                   Studio Apartment         No        Yes
105                       Junior Two Bedroom - 2 Baths         No        Yes
106                                  One-Bedroom Suite         No        Yes
107  Superior, Two Double Beds, Guest room, 2 Doubl...         No        Yes
108  One Bedroom Corner Suite - 1 King bed, living ...         No        Yes

        Price
0    ₹ 21,186
1    ₹ 24,707
2    ₹ 16,976
3    ₹ 11,473
4    ₹ 17,575
..        ...
104  ₹ 15,176
105  ₹ 27,317
106  ₹ 37,097
107  ₹ 46,986
108  ₹ 72,846

[109 rows x 5 columns]

In [49]:
df_Toronto.head()

,Hotel Name,Room Type,Single Bed,Double Bed,Price
0,The Fairview,King Room with Balcony,No,Yes,"₹ 21,186"
1,W Toronto,"Wonderful, Guest room, 1 King, Courtyard view",No,Yes,"₹ 24,707"
2,DoubleTree by Hilton Toronto Downtown,King Room,No,Yes,"₹ 16,976"
3,"Holiday Inn Express Toronto-North York, an IHG...",Standard Queen Room with Two Queen Beds,No,Yes,"₹ 11,473"
4,"Holiday Inn Toronto Downtown Centre, an IHG Hotel",Queen Room - Disability Access,No,Yes,"₹ 17,575"

In [60]:
combined_df = pd.concat([df_Dubai, df_London, df_Malaysia, df_Manchester, df_Delhi, df_Birmingham, df_Berlin, df_Sydney, df_Melbourne,
                        df_Paris, df_Tokyo, df_Toronto], ignore_index=True)

In [61]:
combined_df

,Hotel Name,Room Type,Single Bed,Double Bed,Price
0,Edge Creekside Hotel,Deluxe King Room,No,Yes,"₹ 10,550"
1,Sonder Business Bay,Standard Apartment,No,Yes,"₹ 21,283"
2,ibis Styles Dubai Airport Hotel,"Twin Room - Free DXB Airport Shuttle Drop Off,...",Yes,No,"₹ 7,933"
3,Resivation Hotel,Superior King Room,No,Yes,"₹ 7,241"
4,"Holiday Inn Express Dubai Airport, an IHG Hotel",Double Room - Smoking (Free Shuttle Bus to Air...,No,Yes,"₹ 7,290"
...,...,...,...,...,...
5038,Casa Queen Hotel,Studio Apartment,No,Yes,"₹ 15,176"
5039,Yonge Suites Furnished Apartments,Junior Two Bedroom - 2 Baths,No,Yes,"₹ 27,317"
5040,Le Germain Hotel Maple Leaf Square,One-Bedroom Suite,No,Yes,"₹ 37,097"
5041,The St. Regis Toronto,"Superior, Two Double Beds, Guest room, 2 Doubl...",No,Yes,"₹ 46,986"
5042,"The Ritz-Carlton, Toronto","One Bedroom Corner Suite - 1 King bed, living ...",No,Yes,"₹ 72,846"

In [62]:
combined_df.to_csv('csv3.csv', index=False)

In [53]:
Hotel_price = pd.read_csv('csv3.csv')

In [54]:
Hotel_price.isnull().sum()

Hotel Name    0
Room Type     0
Single Bed    0
Double Bed    0
Price         0
dtype: int64